name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 7.1.0
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  circle_flags: ^1.0.4
  phone_numbers_parser: ^7.0.2
  dart_countries: ^3.0.3
  intl: '>=0.17.0 <= 1.0.0'
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
