name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 3.0.1
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  circle_flags: ^0.0.2
  phone_numbers_parser: ^2.0.1
  dart_countries: ^2.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter  


