name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 9.0.4
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_country_selector: ^1.0.4
  circle_flags: ^4.0.2
  phone_numbers_parser: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
