name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 10.0.3
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.18.0 <=1.0.0"
  flutter_country_selector: ^1.0.13
  circle_flags: ^5.0.0
  phone_numbers_parser: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
