name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 4.5.0
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  circle_flags: ^0.0.2
  phone_numbers_parser: ^4.2.0
  dart_countries: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
